import {HorizontalBox} from "std-widgets.slint";

export struct GalaxyTileItem{
    occupied:bool,
    name: string,
    sun-color:color,
    num-planets:int,
}

export component GalaxyTileView{
    callback clicked();

    in property <GalaxyTileItem> galaxy-model;
    in property <int> x_coord: 0;
    in property <int> y_coord: 0;
    in property <int> index;
    
    out property <bool> selected: false;
    states[
        selected when selected: {
            background.background: #728c91;
        }
        unselected when !selected:{
            background.background: #5d5179;
        }
    ]

    touch-area := TouchArea{
        width: 100%;
        height: 100%;
        clicked => {
            selected = !selected;
            root.clicked();
        }
    }

    HorizontalBox {
        width: 100px;
        height: 100px;
        
        background := Rectangle {
            background: #5d5179;
            border-radius: 10px;
            coord-label := Text{
                y: -self.height / 5;
                x: (self.width) / 3;
                text: "(" + root.x_coord + "," + root.y_coord + ")";
                font-size: 10px;
            }
            galaxy-star := Rectangle{
                y: (parent.height - self.height) / 2.5;
                width: 40px;
                height: self.width;
                border-color: self.background;
                border-radius: self.width / 2;
                background: root.galaxy-model.sun-color;
                visible: root.galaxy-model.occupied;
            }

            galaxy-label := Text {
                y: (parent.height - self.height);
                font-family: "Roboto";
                font-size: 18px;
                color: #94e2a5;
                text: root.galaxy-model.name;
                visible: root.galaxy-model.occupied;
            }
            planet-number-label := Text {
                y: -self.height / 5;
                x: (parent.width - self.width) / 1.2;
                horizontal-alignment: right;
                font-family: "Roboto";
                font-size: 10px;
                color: #94e2a5;
                text: root.galaxy-model.num-planets + " planets";
                visible: root.galaxy-model.occupied;
            }
        }       
    }
}
