export global ColorPallete {
    out property <brush> Color1: #5d5179;
    out property <brush> Color2: #4f5e85;
    out property <brush> Color3: #4f759b;
    out property <brush> Color4: #728c91;
    out property <brush> Color5: #70a094;
    out property <brush> Color6: #6db39c;
    out property <brush> Color7: #92c9b1;
    out property <brush> Color8: #94e2a5;
    out property <brush> Color9: #a2faa3;
}