import { HorizontalBox, VerticalBox } from "std-widgets.slint";
import {GalaxyTileItem} from "../widgets/galaxy_tile.slint";

export global GalaxyDetailAdapter{
    in-out property <GalaxyTileItem> galaxy: {
        name:"System 1", 
        occupied: true, 
        sun-color: Colors.green, 
        num-planets: 6};

    out property <bool> visible;

    callback show_galaxy(GalaxyTileItem);

    show_galaxy(new-galaxy) => {
        visible = true;
        galaxy = new-galaxy;
    }
    
}
export component  GalaxyDetailView {
    callback set-selected-galaxy(GalaxyTileItem);
    callback clear-selected-item;
   
    Rectangle {
        width: 175px;
        height: 100%;
        background: #4f759b;
        border-radius: 10px;
    
        layout := VerticalBox {
            width: 175px;
            
            title := Text {
                text: "Selected Galaxy Overview";
                font-family: "Roboto";
                font-size: 24px;
                height: 125px;
                color: yellow;
            }
            selected-system-name-label := Text{
                height: self.font-size * 1.1;
                font-size: 18px;
                text: GalaxyDetailAdapter.galaxy.name;
                visible: GalaxyDetailAdapter.visible;
            }
            selected-system-number-planets-label := Text{
                height: self.font-size * 1.1;
                text: GalaxyDetailAdapter.galaxy.num-planets + " planets";
                font-size: 16px;
                visible: GalaxyDetailAdapter.visible;
            }
            selected-system-label := Text{
                height: self.font-size * 1.1;
                text: "Sun is this color";
                font-size: 18px;
                font-weight: 700;
                color: GalaxyDetailAdapter.galaxy.sun-color;
                visible: GalaxyDetailAdapter.visible;
            }
        }
    }
}