import { HorizontalBox, VerticalBox } from "std-widgets.slint";
import {GalaxyTileItem} from "../widgets/galaxy_tile.slint";

export component  GalaxyDetailView {
    callback set-selected-galaxy(GalaxyTileItem);
    callback clear-selected-item;
    
    set-selected-galaxy(new-selected-item) => {
        details-visible = true;
        selected-galaxy = new-selected-item;
    }
    clear-selected-item => {
        details-visible = false;
    }
    
    property <GalaxyTileItem> selected-galaxy: {
        name:"System 1", 
        occupied: true, 
        sun-color: Colors.green, 
        num-planets: 6};
    property <bool> details-visible: true;

    layout := VerticalBox {
        width: 175px;
        title := Text {
            text: "Selected Galaxy Overview";
            font-family: "Roboto";
            font-size: 24px;
            height: 125px;
            color: yellow;
        }
        selected-system-name-label := Text{
            height: self.font-size * 1.1;
            font-size: 18px;
            text: selected-galaxy.name;
            visible: root.details-visible;
        }
        selected-system-number-planets-label := Text{
            height: self.font-size * 1.1;
            text: selected-galaxy.num-planets + " planets";
            font-size: 16px;
            visible: root.details-visible;
        }
        selected-system-label := Text{
            height: self.font-size * 1.1;
            text: "Sun is this color";
            font-size: 18px;
            font-weight: 700;
            color: root.selected-galaxy.sun-color;
            visible: root.details-visible;
        }
    }
}