import {GalaxyTileView,GalaxyTileItem} from "../widgets/galaxy_tile.slint";
import { VerticalBox, HorizontalBox } from "std-widgets.slint";

export global UniverseOverviewAdapter{
    
}
export component UniverseOverviewView {
    in-out property <[GalaxyTileItem]> model:[
        {name:"System 1", occupied: true},
        {name:"System 2", occupied: true},
        {name:"System 3", occupied: false},
        {name:"System 4", occupied: true},
        {name:"System 5", occupied: true},
        {name:"System 6", occupied: true},
        {name:"System 7", occupied: true},
        {name:"System 8", occupied: true},
        {name:"System 9", occupied: true},
        {name:"System 10", occupied: true},
        {name:"System 11", occupied: true},
        {name:"System 12", occupied: true},
        {name:"System 13", occupied: true},
        {name:"System 14", occupied: true},
        {name:"System 15", occupied: true},
        
    ];

    in property <int> view-columns: 8;
    in property <int> view-rows: 7;
    
    HorizontalBox {
        width: view-columns * 100px;
        height: view-rows * 100px;

        for column in view-columns: VerticalBox {
            for row in view-rows:
                GalaxyTileView {
                    name: root.model[root.view-columns * column + row].name;
                }
            
            
        }
    }
    
}